### ISSUE TITLE
Target time range

### ISSUE THREAD

**Issue by ThomKaar** [ThomKaar/CSC369-Lab4#2]
With each analytical query, a time range can be specified. By default, the
time range is the entire range of dates in the collection. If a range is specified, it will contain both
the upper and the lower boundary, and the boundaries will always be inclusive.

**Comment by wbenica** [comment]
I set it so the "states" collection dates are stored in the same format as the covid dates: YYYYMMDD integers.

**Comment by wbenica** [comment]
the analysis options for time range are "today", "tomorrow", "week", "month", and "{start: xx, end: xx}", so to make it easier (I think), I'm storing them all in the start/end format, so that all ranges can just be done like this:
`{ $match: {date: {$gte: start, $lte: end} }`

**Comment by ThomKaar** [comment]
I've pushed to the branch time_range, I haven't made a PR because it isn't running. 
The error is:
`Traceback (most recent call last):
  File "covidTracker.py", line 37, in <module>
    main()
  File "covidTracker.py", line 25, in main
    pipeline = create_pipeline(test_config)
  File "/home/tkaar/lab4/CSC369-Lab4/pipeline.py", line 23, in create_pipeline
    aggregation = create_facet_stage(test_config)
  File "/home/tkaar/lab4/CSC369-Lab4/pipeline.py", line 68, in create_facet_stage
    if "ratio" in query['task']:
KeyError: 'task'`

**Comment by wbenica** [comment]
I don't get that error when I'm running it. Does the "analysis" property in your trackerConfig.json file look like:
`{ ... "analysis": [ { "task": { ... }, "output": { ... } }, { "task": { ... }, "output": { ... } } ], ... }
`
In other words, "analysis" is an array of 1 or more objects, and each object has two fields, "task" and "output"?

**Comment by wbenica** [comment]
Didn't mean to close it

**Comment by ThomKaar** [comment]
This is my analysis object within trackerConfig.json:
```
"analysis": [
    {
      "task": {
        "track": "positive"
      }
    },
    {
      "output": {
        "graph": {
          "type": "scatter",
          "legend": "on",
          "combo": "split",
          "title": "Covid Cases this month"
        }
      }
    }
  ]
```

**Comment by ThomKaar** [comment]
Do I need to add another task to the analysis? I just copied the trackerConfig.json that you removed in PR #21. Maybe I don't understand that removal correctly. Thanks for you help on this!

**Comment by wbenica** [comment]
It's hard to keep track of all the braces--I stared at this for a while and couldn't figure out what was wrong. I think there were a couple of extra braces in between "track" and "output", so I think it should look like this

```
"analysis": [
    {
      "task": {
        "track": "positive"
      },
      "output": {
        "graph": {
          "type": "scatter",
          "legend": "on",
          "combo": "split",
          "title": "Covid Cases this month"
        }
      }
    }
  ]
```

**Comment by ThomKaar** [comment]
Thank you! That worked!
