### ISSUE TITLE
Output - Table: modify when col = time, row = state/county

### ISSUE THREAD

**Issue by wbenica** [ThomKaar/CSC369-Lab4#30]
I've got it working as long as row == time, but it's not set up if col == time.

**Comment by wbenica** [comment]
now that the data is converted to dataframes, this is a quick fix: switch df index/columns based on row/column values.

**Comment by ThomKaar** [comment]
branching and starting this one now

**Comment by ThomKaar** [comment]
Looks like you fixed it in #33 line 13 of output_table.py
